export enum FFComponent {
  FORM = 'FORM',
  FIELD = 'FIELD',
  STEP = 'STEP',
  SHOW_DATA = 'SHOW_DATA',
  SUBMIT = 'SUBMIT',
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  COLOR = 'COLOR',
  EMAIL = 'EMAIL',
  PASSWORD = 'PASSWORD',
  TEL = 'TEL',
  TEXTAREA = 'TEXTAREA',
  URL = 'URL',
}
